package com.anz.wholesale.util;


public class AccountAndTransactionSql {

	public static final String ACCOUNT_LIST_DETAILS = "SELECT ACCOUNT_NUMBER, ACCOUNT_NAME,ACCOUNT_TYPE, BALANCE_TYPE,CURRENCY,OPENING_AVAILABLE_BALANCE FROM ACCOUNT_DETAILS";
	
	public static final String TRANSACTION_ON_SPECIFIC_ACCOUNTS_DETAILS = "SELECT ACCOUNT_NUMBER,ACCOUNT_NAME, VALUE_DATE, CURRENCY,DEBIT_AMOUNT,CREDIT_AMOUNT, DEBIT_OR_CREDIT, TRANSACTION_NARRATIVE WHERE ACCCOUNT_NUMBER = :accountNumber";
	
	public static final String IS_ACCOUNT_EXIST = "SELECT ACCOUNT_NUMBER WHERE ACCCOUNT_NUMBER = :accountNumber";
	
	
}
